[package]
name = "composite-error"
version = "0.1.0"
authors = ["Dezajno <dezajno@junk.studio>"]
edition = "2018"

[dependencies]
syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0.9"

[lib]
proc-macro = true

